
INSERT INTO public.help_categories (slug, title, description, icon, sort_order) VALUES
 ('getting-started','Getting Started','Set up your business and go live in under an hour.','Rocket',1),
 ('bookings','Bookings & Jobs','Create, schedule, reschedule and complete work.','CalendarDays',2),
 ('customers','Customers','Build your customer list and keep great records.','Users',3),
 ('services','Services & Pricing','Define what you sell and how it is priced.','Tag',4),
 ('team','Team','Add staff, set availability and assign work.','UsersRound',5),
 ('payments','Payments & Invoices','Get paid online, track deposits and balances.','CreditCard',6),
 ('automations','Automations & Messages','Email and SMS confirmations, reminders and follow-ups.','Zap',7),
 ('leads','Leads & Marketing','Capture leads from your website and turn them into jobs.','TrendingUp',8),
 ('reports','Reports & Analytics','Understand revenue, jobs and team performance.','BarChart3',9),
 ('settings','Settings & Account','Business profile, billing, integrations and permissions.','Settings',10)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.help_articles (category_slug, slug, title, description, keywords, steps, body, routes, related_slugs, sort_order) VALUES
('getting-started','welcome','Welcome to Solutionary HQ','A quick tour of how the software works, start to finish.',
 ARRAY['welcome','tour','overview','start'],
 '["Quotes: send a price to a customer.","Bookings & Jobs: schedule the work on your calendar.","Field View: your crew completes the checklist and takes photos.","Invoices: collect the balance online.","Reviews: ask happy customers for a review automatically."]'::jsonb,
 'Solutionary HQ follows one simple flow: Quote to Approve to Schedule to Work to Invoice to Pay to Review. Everything in the left menu supports one of those steps.',
 ARRAY['/dashboard'], ARRAY['setup-business','first-service','launch-booking-page'],1),
('getting-started','setup-business','Setting up your business','Add your business name, industry, phone and logo.',
 ARRAY['business','profile','setup','logo','industry'],
 '["Open Settings from the left menu.","Fill in your business name, phone and address.","Choose the industry that matches your company.","Upload your logo so it appears on quotes, invoices and your booking page.","Click Save."]'::jsonb,
 'Your business profile is used on every customer-facing page, email and invoice, so complete it first.',
 ARRAY['/dashboard/settings'], ARRAY['welcome','business-settings','launch-booking-page'],2),
('getting-started','first-service','Adding your first service','Create the services customers can book and get priced.',
 ARRAY['service','first','price','create'],
 '["Go to Services.","Click Add Service.","Enter the service name and a short description.","Set the price and how long the job usually takes.","Save. The service now appears in quotes and on your booking page."]'::jsonb,
 null, ARRAY['/dashboard/services'], ARRAY['create-service','service-pricing','service-addons'],3),
('getting-started','add-team','Adding team members','Invite the people who will do the work.',
 ARRAY['team','staff','employee','invite'],
 '["Go to Team.","Click Add Team Member.","Enter their name, email, phone and role.","Save. You can now assign them to jobs on the calendar."]'::jsonb,
 null, ARRAY['/dashboard/team'], ARRAY['team-availability','assign-team-member','team-permissions'],4),
('getting-started','set-availability','Setting availability','Tell the system when your team can work.',
 ARRAY['availability','hours','schedule','working hours'],
 '["Go to Team Schedule.","Pick a team member.","Set the days and hours they are available.","Save. Booking and scheduling will respect these hours."]'::jsonb,
 null, ARRAY['/dashboard/team/schedule'], ARRAY['add-team','assign-team-member','booking-conflicts'],5),
('getting-started','setup-booking','Setting up your booking system','Configure the online booking form customers use.',
 ARRAY['booking','wizard','form','online booking'],
 '["Go to Booking Wizard settings.","Choose which services and add-ons appear.","Set your pricing rules and any minimums.","Preview the form using the Book Now button at the top of the menu.","Save."]'::jsonb,
 null, ARRAY['/dashboard/cleaning-wizard-config'], ARRAY['launch-booking-page','embed-widget','online-deposits'],6),
('getting-started','setup-payments','Setting up payments','Turn on online card payments and deposits.',
 ARRAY['payments','stripe','deposit','card'],
 '["Go to Settings and open the payments section.","Connect your payment account.","Choose whether customers pay a 25%, 50% or 100% deposit when booking.","Save and place a small test booking to confirm it works."]'::jsonb,
 null, ARRAY['/dashboard/settings','/dashboard/invoices'], ARRAY['online-deposits','collect-payment','refunds'],7),
('getting-started','setup-notifications','Setting up notifications','Choose the emails and texts your customers receive.',
 ARRAY['notifications','email','sms','reminders'],
 '["Go to Automations.","Turn on booking confirmations.","Turn on appointment reminders and pick how far ahead they send.","Turn on follow-up and review requests.","Save."]'::jsonb,
 null, ARRAY['/dashboard/cleaning-automations'], ARRAY['email-notifications','sms-notifications','appointment-reminders'],8),
('getting-started','launch-booking-page','Launching your booking page','Share your booking link so customers can book themselves.',
 ARRAY['booking page','link','share','publish','website'],
 '["Click Book Now at the top of the left menu to preview your page.","Use the copy icon next to it to copy your public link.","Share the link on your website, Google profile and social media.","Optional: open Website Builder to generate a full website."]'::jsonb,
 null, ARRAY['/dashboard/website'], ARRAY['embed-widget','website-builder','website-leads'],9),
('getting-started','first-booking','Creating your first booking','Book a job end to end in about a minute.',
 ARRAY['first booking','create booking','job','schedule'],
 '["Open Calendar and click an open time slot.","Choose or add the customer.","Choose the service.","Confirm the date and time.","Assign a team member.","Review and save the booking."]'::jsonb,
 null, ARRAY['/dashboard/calendar','/dashboard/jobs'], ARRAY['create-booking','assign-team-member','booking-statuses'],10),

('bookings','create-booking','Creating a booking','Add a job to the calendar for a customer.',
 ARRAY['create','booking','job','new job','schedule'],
 '["Go to Calendar or Jobs.","Click New Job or an empty time slot.","Select the customer (or add a new one).","Select the service and enter any job details.","Pick the date and start time.","Assign a team member.","Save to confirm the booking."]'::jsonb,
 null, ARRAY['/dashboard/jobs','/dashboard/calendar'], ARRAY['reschedule-booking','cancel-booking','assign-team-member'],1),
('bookings','manage-bookings','Managing bookings','Find, filter and update any job.',
 ARRAY['manage','jobs list','filter','search'],
 '["Go to Jobs.","Use search or the status filters to find the job.","Click the job to open its details.","Update details, notes, photos or status, then save."]'::jsonb,
 null, ARRAY['/dashboard/jobs'], ARRAY['booking-statuses','booking-details','reschedule-booking'],2),
('bookings','reschedule-booking','Rescheduling a booking','Move a job to a new date or time.',
 ARRAY['reschedule','move','change date','drag'],
 '["Open Calendar.","Drag the job to the new day or time slot, or open the job and edit the date.","If the new time conflicts with another job for that team member, you will be warned.","Save. The customer can be notified automatically."]'::jsonb,
 null, ARRAY['/dashboard/calendar'], ARRAY['cancel-booking','booking-conflicts','appointment-reminders'],3),
('bookings','cancel-booking','Canceling a booking','Cancel a job and free up the time slot.',
 ARRAY['cancel','cancellation','delete job'],
 '["Open the job from Jobs or the Calendar.","Change the status to Cancelled.","Add a short note explaining why.","Save. The slot becomes available again."]'::jsonb,
 null, ARRAY['/dashboard/jobs'], ARRAY['reschedule-booking','booking-statuses'],4),
('bookings','assign-team-member','Assigning a team member','Give a job to the right person on your crew.',
 ARRAY['assign','technician','crew','staff'],
 '["Open the job.","Use the Assign field to choose a team member.","Save. The job appears in their Field View.","Conflicts with their other jobs are blocked automatically."]'::jsonb,
 null, ARRAY['/dashboard/jobs','/dashboard/calendar','/dashboard/team'], ARRAY['booking-conflicts','team-availability','field-view'],5),
('bookings','booking-statuses','Understanding booking statuses','What each job status means.',
 ARRAY['status','scheduled','in progress','completed','cancelled'],
 '["Scheduled: booked and on the calendar.","In Progress: the crew has started.","Completed: work finished, ready to invoice.","Cancelled: the job will not happen."]'::jsonb,
 null, ARRAY['/dashboard/jobs'], ARRAY['manage-bookings','create-invoice'],6),
('bookings','recurring-bookings','Recurring bookings','Set up weekly, bi-weekly or monthly repeat visits.',
 ARRAY['recurring','repeat','weekly','biweekly','monthly'],
 '["Go to Recurring.","Click New Recurring Plan.","Choose the customer, service and frequency.","Set the start date and preferred time.","Save. Visits are generated on schedule."]'::jsonb,
 null, ARRAY['/dashboard/recurring-cleanings'], ARRAY['create-booking','recurring-services'],7),
('bookings','booking-details','Managing booking details','Notes, checklists, photos and sign-off on a job.',
 ARRAY['details','notes','photos','checklist','signature'],
 '["Open the job.","Add access notes such as gate codes or pet information.","Attach the right checklist template.","Crews add before and after photos in Field View.","Capture the customer signature when the work is done."]'::jsonb,
 null, ARRAY['/dashboard/jobs'], ARRAY['checklists','field-view','create-invoice'],8),
('bookings','booking-conflicts','Preventing double bookings','How scheduling conflicts are blocked.',
 ARRAY['conflict','double booking','overlap'],
 '["When you assign or move a job, overlapping times for the same team member are rejected.","You will see a message telling you who is already booked.","Pick another time or another team member."]'::jsonb,
 null, ARRAY['/dashboard/calendar'], ARRAY['assign-team-member','team-availability'],9),
('bookings','field-view','Using Field View in the field','The mobile screen your crew uses on site.',
 ARRAY['field','mobile','technician','on site','app'],
 '["Your team opens Field View on their phone.","They see only the jobs assigned to them.","They start the job, work the checklist and take photos.","They collect a signature and mark the job complete."]'::jsonb,
 null, ARRAY['/dashboard/field'], ARRAY['checklists','booking-details','team-permissions'],10),
('bookings','checklists','Using checklists','Standardize quality on every visit.',
 ARRAY['checklist','template','quality','tasks'],
 '["Go to Checklists.","Create a template and add the tasks room by room.","Mark tasks that require a photo.","Attach the template to a service or job.","Crews must finish the checklist before completing the job."]'::jsonb,
 null, ARRAY['/dashboard/checklist-templates'], ARRAY['field-view','booking-details'],11),

('customers','add-customer','Adding a customer','Create a customer record manually.',
 ARRAY['add','new customer','create'],
 '["Go to Customers.","Click Add Customer.","Enter their name, email, phone and service address.","Save."]'::jsonb,
 null, ARRAY['/dashboard/customers'], ARRAY['customer-profiles','edit-customer','customer-notes'],1),
('customers','customer-profiles','Customer profiles','Everything stored about one customer.',
 ARRAY['profile','record','details'],
 '["Open Customers and click a name.","Contact details and addresses are at the top.","Quotes, jobs and invoices for that customer are listed below.","Notes and preferences are saved on the same screen."]'::jsonb,
 null, ARRAY['/dashboard/customers'], ARRAY['customer-history','customer-notes'],2),
('customers','customer-history','Customer history','See every job, quote and payment for a customer.',
 ARRAY['history','past jobs','activity'],
 '["Open the customer profile.","Scroll to the activity lists.","Click any quote, job or invoice to open it."]'::jsonb,
 null, ARRAY['/dashboard/customers'], ARRAY['customer-profiles','manage-bookings'],3),
('customers','customer-notes','Customer notes and preferences','Record gate codes, pets and special instructions.',
 ARRAY['notes','pets','gate code','instructions','preferences'],
 '["Open the customer profile.","Add notes in the notes field.","Save. Notes are visible to crews on the job."]'::jsonb,
 null, ARRAY['/dashboard/customers'], ARRAY['customer-profiles','booking-details'],4),
('customers','edit-customer','Editing or deleting a customer','Fix details or remove a record.',
 ARRAY['edit','update','delete','remove'],
 '["Go to Customers and find the person.","Click Edit to change their details, then Save.","Click Delete to remove the record permanently."]'::jsonb,
 null, ARRAY['/dashboard/customers'], ARRAY['add-customer','customer-profiles'],5),
('customers','customer-portal','The customer portal','Let customers view their bookings without a password.',
 ARRAY['portal','magic link','customer login'],
 '["Open the customer profile.","Send a portal link by email.","The customer clicks the link and sees their upcoming visits, quotes and invoices."]'::jsonb,
 null, ARRAY['/dashboard/customers'], ARRAY['customer-history','collect-payment'],6),

('services','create-service','Creating a service','Add something customers can buy.',
 ARRAY['create service','add service','new'],
 '["Go to Services.","Click Add Service.","Name the service and write a short customer-friendly description.","Set the price and duration.","Save."]'::jsonb,
 null, ARRAY['/dashboard/services'], ARRAY['service-pricing','service-duration','service-addons'],1),
('services','service-pricing','Service pricing','Flat prices, square-foot tiers and frequency discounts.',
 ARRAY['pricing','price','tiers','sqft','discount'],
 '["Open Services and edit a service to set its base price.","Use pricing rules for square-footage tiers.","Set frequency discounts for weekly, bi-weekly and monthly plans.","Save. Quotes and the booking form use these prices automatically."]'::jsonb,
 null, ARRAY['/dashboard/services','/dashboard/call-quote-console'], ARRAY['create-service','service-addons','call-quote-console'],2),
('services','service-duration','Service duration','How long a job blocks on the calendar.',
 ARRAY['duration','time','length'],
 '["Edit the service.","Set the typical duration in minutes or hours.","Save. The calendar reserves that much time per booking."]'::jsonb,
 null, ARRAY['/dashboard/services'], ARRAY['create-service','set-availability'],3),
('services','service-addons','Add-ons','Extras like fridge, oven or window cleaning.',
 ARRAY['addons','extras','upsell'],
 '["Open your booking or quote settings.","Add each extra with its own price.","Save. Customers can select add-ons when booking and prices update live."]'::jsonb,
 null, ARRAY['/dashboard/services','/dashboard/cleaning-wizard-config'], ARRAY['service-pricing','setup-booking'],4),
('services','service-availability','Service availability','Control when a service can be booked.',
 ARRAY['availability','when','slots'],
 '["Set your team availability in Team Schedule.","Limit which services appear in the booking form settings.","Save."]'::jsonb,
 null, ARRAY['/dashboard/services'], ARRAY['set-availability','setup-booking'],5),
('services','recurring-services','Recurring services','Offer discounted repeat plans.',
 ARRAY['recurring','plan','subscription'],
 '["Enable frequency options for the service.","Set the discount for weekly, bi-weekly and monthly.","Save. Customers choose their frequency when booking."]'::jsonb,
 null, ARRAY['/dashboard/services','/dashboard/recurring-cleanings'], ARRAY['recurring-bookings','service-pricing'],6),
('services','manage-services','Managing services','Edit, reorder or remove services.',
 ARRAY['manage','edit','delete','packages'],
 '["Go to Services.","Edit a service to change its details.","Delete services you no longer offer.","Use Packages to bundle services at a set price."]'::jsonb,
 null, ARRAY['/dashboard/services','/dashboard/cleaning-packages'], ARRAY['create-service','service-pricing'],7),

('team','add-employee','Adding employees and contractors','Bring your crew into the system.',
 ARRAY['employee','contractor','add','hire','staff'],
 '["Go to Team.","Click Add Team Member.","Enter their details and choose employee or contractor.","Pick a role: admin, manager or technician.","Save."]'::jsonb,
 null, ARRAY['/dashboard/team'], ARRAY['team-permissions','team-availability','team-payroll'],1),
('team','team-availability','Team availability','Set the hours each person can work.',
 ARRAY['availability','hours','shift','schedule'],
 '["Go to Team Schedule.","Select the team member.","Set their working days and hours.","Save."]'::jsonb,
 null, ARRAY['/dashboard/team/schedule'], ARRAY['assign-team-member','booking-conflicts'],2),
('team','team-permissions','Team permissions','What each role can see and do.',
 ARRAY['permissions','roles','access','privacy'],
 '["Admins can see everything, including invoices and revenue.","Managers can schedule and manage jobs and customers.","Technicians only see their own jobs, checklists and their own earnings.","Change a role by editing the team member."]'::jsonb,
 'Invoices and company revenue are hidden from technicians by design.',
 ARRAY['/dashboard/team','/dashboard/team-hq'], ARRAY['add-employee','team-payroll'],3),
('team','team-payroll','Time tracking and payroll','Track hours and pay from Team HQ.',
 ARRAY['payroll','hours','time','earnings','clock'],
 '["Crews clock in and out from Field View.","Open Team HQ to review hours by person and date.","Adjust entries if needed.","Use the totals to run payroll."]'::jsonb,
 null, ARRAY['/dashboard/team-hq'], ARRAY['add-employee','team-permissions'],4),

('payments','collect-payment','Collecting a payment','Get paid by card online.',
 ARRAY['collect','pay','card','stripe','checkout'],
 '["Open the invoice.","Click Send so the customer receives a payment link.","The customer pays by card on a secure page.","The invoice is marked paid automatically."]'::jsonb,
 null, ARRAY['/dashboard/invoices'], ARRAY['create-invoice','payment-status','online-deposits'],1),
('payments','create-invoice','Creating an invoice','Bill a completed job.',
 ARRAY['invoice','bill','create'],
 '["Go to Invoices and click New Invoice, or invoice directly from a completed job.","Choose the customer and add line items.","Check the total and due date.","Save and send."]'::jsonb,
 null, ARRAY['/dashboard/invoices'], ARRAY['collect-payment','payment-status'],2),
('payments','payment-status','Payment statuses','Draft, sent, paid and overdue explained.',
 ARRAY['status','paid','overdue','sent','draft'],
 '["Draft: not sent yet.","Sent: waiting on the customer.","Paid: money received in full.","Overdue: past the due date and unpaid."]'::jsonb,
 null, ARRAY['/dashboard/invoices'], ARRAY['collect-payment','refunds'],3),
('payments','online-deposits','Deposits on online bookings','Ask for 25%, 50% or the full amount at booking.',
 ARRAY['deposit','25','50','prepay','booking payment'],
 '["Open your booking settings.","Turn on deposits and choose the allowed options.","Save. Customers see Pay and Book Now with the deposit choices.","The paid amount is recorded on the booking."]'::jsonb,
 null, ARRAY['/dashboard/settings','/dashboard/booking-requests'], ARRAY['setup-payments','collect-payment'],4),
('payments','refunds','Refunds','Return money to a customer.',
 ARRAY['refund','money back','return'],
 '["Open the paid invoice or booking.","Issue the refund from your payment provider record.","Add a note on the invoice so your records match."]'::jsonb,
 null, ARRAY['/dashboard/invoices'], ARRAY['payment-status','collect-payment'],5),
('payments','customer-payment-info','Customer payment information','What card data is stored.',
 ARRAY['card','security','pci','stored'],
 '["Card numbers are never stored in Solutionary HQ.","Payments are processed by our PCI-compliant payment provider.","You only see the amount, status and a payment reference."]'::jsonb,
 null, ARRAY['/dashboard/invoices'], ARRAY['collect-payment'],6),

('automations','booking-confirmations','Booking confirmations','Confirm every booking instantly.',
 ARRAY['confirmation','confirm','automatic'],
 '["Go to Automations.","Turn on booking confirmation messages.","Edit the wording if you want.","Save."]'::jsonb,
 null, ARRAY['/dashboard/cleaning-automations'], ARRAY['email-notifications','sms-notifications'],1),
('automations','email-notifications','Email notifications','Quotes, invoices, receipts and reminders by email.',
 ARRAY['email','notify','template'],
 '["Go to Automations.","Turn on the email messages you want to send.","Save. Emails are sent from your business name."]'::jsonb,
 null, ARRAY['/dashboard/cleaning-automations'], ARRAY['booking-confirmations','review-requests'],2),
('automations','sms-notifications','SMS notifications','Text your customers from your business number.',
 ARRAY['sms','text','twilio','phone'],
 '["Connect your business phone number in Settings.","Go to Automations and turn on the text messages you want.","Save. Replies come back into the software."]'::jsonb,
 null, ARRAY['/dashboard/cleaning-automations','/dashboard/settings'], ARRAY['email-notifications','appointment-reminders'],3),
('automations','appointment-reminders','Appointment reminders','Cut no-shows with automatic reminders.',
 ARRAY['reminder','no show','before'],
 '["Go to Automations.","Turn on appointment reminders.","Choose how many hours before the visit they send.","Save."]'::jsonb,
 null, ARRAY['/dashboard/cleaning-automations'], ARRAY['booking-confirmations','sms-notifications'],4),
('automations','review-requests','Follow-ups and review requests','Ask for a review right after the job.',
 ARRAY['review','follow up','rating','feedback'],
 '["Go to Automations and turn on review requests.","When a job is marked completed the customer gets a link.","Reviews appear under Reviews and on your public review page."]'::jsonb,
 null, ARRAY['/dashboard/reviews','/dashboard/cleaning-automations'], ARRAY['email-notifications','manage-reviews'],5),

('leads','manage-leads','Managing leads','Work every new enquiry to a booking.',
 ARRAY['leads','enquiry','requests','pipeline'],
 '["Go to Requests to see new enquiries.","Open one to review the details.","Send a quote or book the job directly.","Mark it won or lost so your numbers stay accurate."]'::jsonb,
 null, ARRAY['/dashboard/service-requests','/dashboard/booking-requests'], ARRAY['website-leads','missed-leads','call-quote-console'],1),
('leads','website-leads','Website and widget leads','Every form submission lands in your CRM.',
 ARRAY['website','widget','embed','wordpress','form'],
 '["Copy your booking or quote widget code from the sharing settings.","Paste it into your website.","Submissions create the customer and the request automatically.","Find them under Requests and Customers."]'::jsonb,
 null, ARRAY['/dashboard/service-requests'], ARRAY['embed-widget','manage-leads'],2),
('leads','missed-leads','Missed calls and lost leads','Follow up on the ones that got away.',
 ARRAY['missed','call','voicemail','lost'],
 '["Open Missed Leads.","Review missed calls and voicemails with their summaries.","Call or text back from the record.","Convert to a quote when they are ready."]'::jsonb,
 null, ARRAY['/dashboard/missed-leads'], ARRAY['manage-leads','call-quote-console'],3),
('leads','call-quote-console','Call-time quote console','Price a job live while the customer is on the phone.',
 ARRAY['call','phone','quote','console','sales'],
 '["Open Call Quote Console.","Pick the square-footage tier and room counts.","Add extras and choose the cleaning frequency.","The customer sees the same price you do on a live link.","Send the quote by text or email and take payment."]'::jsonb,
 null, ARRAY['/dashboard/call-quote-console'], ARRAY['service-pricing','manage-leads'],4),
('leads','marketing-campaigns','Campaigns and referrals','Bring past customers back.',
 ARRAY['marketing','campaign','referral','promotion'],
 '["Go to Marketing.","Create a campaign and pick who receives it.","Write the message and send or schedule it.","Track responses from the same screen."]'::jsonb,
 null, ARRAY['/dashboard/marketing'], ARRAY['review-requests','manage-leads'],5),
('leads','embed-widget','Embedding the booking widget','Put booking on any website.',
 ARRAY['embed','iframe','widget','qr'],
 '["Open the sharing settings.","Copy the embed code or the direct link.","Paste the code into your website page.","Test a booking to confirm it works."]'::jsonb,
 null, ARRAY['/dashboard/settings','/dashboard/website'], ARRAY['website-leads','launch-booking-page'],6),
('leads','website-builder','Building your website','Generate a full SEO website for your business.',
 ARRAY['website','builder','seo','generate','pages'],
 '["Open Website Builder.","Click Generate My Website.","Review the generated pages and edit any text.","Use the menu editor to arrange your navigation.","Publish and share the link."]'::jsonb,
 null, ARRAY['/dashboard/website'], ARRAY['launch-booking-page','embed-widget'],7),

('reports','revenue-reports','Revenue reports','See what you earned and when.',
 ARRAY['revenue','money','income','reports'],
 '["Open Analytics.","Review total and monthly revenue.","Compare periods to spot trends."]'::jsonb,
 null, ARRAY['/dashboard/analytics'], ARRAY['booking-reports','accounting'],1),
('reports','booking-reports','Booking and job reports','Volume, completion and conversion.',
 ARRAY['jobs','bookings','conversion','reports'],
 '["Open Analytics.","Review jobs booked, completed and cancelled.","Check your quote-to-job conversion rate."]'::jsonb,
 null, ARRAY['/dashboard/analytics','/dashboard/cleaning-analytics'], ARRAY['revenue-reports','team-performance'],2),
('reports','customer-reports','Customer reports','New versus repeat customers.',
 ARRAY['customers','repeat','retention'],
 '["Open Analytics.","Review new and returning customer counts.","Use Marketing to re-engage inactive customers."]'::jsonb,
 null, ARRAY['/dashboard/analytics'], ARRAY['marketing-campaigns','customer-history'],3),
('reports','team-performance','Team performance','Jobs, hours and output per person.',
 ARRAY['team','performance','hours','productivity'],
 '["Open Team HQ.","Review hours worked and jobs completed per person.","Compare across the date range you choose."]'::jsonb,
 null, ARRAY['/dashboard/team-hq','/dashboard/analytics'], ARRAY['team-payroll','booking-reports'],4),
('reports','accounting','Accounting','Track expenses and profitability.',
 ARRAY['accounting','expenses','profit','costs'],
 '["Open Accounting.","Record expenses as they happen.","Compare income against costs to see profit."]'::jsonb,
 null, ARRAY['/dashboard/accounting'], ARRAY['revenue-reports'],5),

('settings','business-settings','Business settings','Name, contact details, branding and public link.',
 ARRAY['settings','business','branding','slug'],
 '["Open Settings.","Update your business details and logo.","Edit your public link if you want a cleaner web address.","Save."]'::jsonb,
 null, ARRAY['/dashboard/settings'], ARRAY['setup-business','change-industry'],1),
('settings','change-industry','Changing your industry','Fix the industry if it was set incorrectly.',
 ARRAY['industry','change','wrong industry'],
 '["Open Settings.","Find the industry selector.","Choose the correct industry and confirm.","Save. Industry-specific tools update in your menu."]'::jsonb,
 null, ARRAY['/dashboard/settings'], ARRAY['business-settings'],2),
('settings','user-permissions','User permissions','Control who can see sensitive information.',
 ARRAY['permissions','roles','access'],
 '["Open Team.","Edit a team member and change their role.","Save. Access updates immediately."]'::jsonb,
 null, ARRAY['/dashboard/team'], ARRAY['team-permissions','add-employee'],3),
('settings','integrations','Integrations','Payments, phone number and email sending.',
 ARRAY['integrations','stripe','twilio','email','connect'],
 '["Open Settings.","Connect your payment account for card payments.","Connect a phone number for calls and texts.","Verify your sending domain for email.","Save."]'::jsonb,
 null, ARRAY['/dashboard/settings'], ARRAY['setup-payments','sms-notifications'],4),
('settings','billing','Billing and your plan','Manage your Solutionary HQ subscription.',
 ARRAY['billing','plan','subscription','upgrade'],
 '["Open Settings.","Find the subscription section.","Upgrade, downgrade or update your card.","Changes take effect right away."]'::jsonb,
 null, ARRAY['/dashboard/settings'], ARRAY['business-settings'],5),
('settings','offline-mode','Working offline','What happens when your crew loses signal.',
 ARRAY['offline','sync','no signal','pwa'],
 '["Field View keeps working without a connection.","Changes are queued on the device.","When signal returns everything syncs automatically.","Check Offline and Sync to see anything still pending."]'::jsonb,
 null, ARRAY['/dashboard/offline','/dashboard/field'], ARRAY['field-view'],6)
ON CONFLICT (slug) DO NOTHING;
